language: php

matrix:
  include:
  - php: 7.0
  - php: 7.1
  - php: hhvm

  allow_failures:
    - php: hhvm

before_install:
  - if [[ $TRAVIS_PHP_VERSION = hhv* ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit --verbose
